name: digital_wind_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  auto_route: ^7.8.4
  http: ^1.2.1
  phone_form_field: ^9.2.3
  flutter_sizer: ^1.0.5
  intl: ^0.18.1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/appIcon.png
    - lib/resources/images/avatar/
    - lib/resources/images/avatar/hat/
    - lib/resources/images/avatar/hair/
    - lib/resources/images/avatar/face/
    - lib/resources/images/avatar/eyes/
    - lib/resources/images/avatar/mouth/
    - lib/resources/images/avatar/clothes/